# Generated by Django 4.0.5 on 2022-12-20 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appoint_id', models.AutoField(primary_key=True, serialize=False)),
                ('appoint_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor_name', models.CharField(max_length=100, unique=True)),
                ('doctor_mobile_number', models.CharField(max_length=16)),
                ('doctor_specialization', models.CharField(max_length=300)),
                ('doctor_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=100, unique=True)),
                ('patient_address', models.CharField(blank=True, max_length=200, null=True)),
                ('patient_email', models.EmailField(max_length=254)),
                ('patient_health_record', models.CharField(max_length=300)),
                ('patient_mobile_number', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('pharmacy_id', models.AutoField(primary_key=True, serialize=False)),
                ('pharmacy_email', models.EmailField(max_length=254)),
                ('pharmacy_address', models.CharField(max_length=200)),
            ],
        ),
    ]
